// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzlo5vz4q4cpjRnomC8IIcl7uJ8_-SFU0',
    appId: '1:48127143523:web:c74b2b49751c7330761256',
    messagingSenderId: '48127143523',
    projectId: 'flutterteam3-724be',
    authDomain: 'flutterteam3-724be.firebaseapp.com',
    storageBucket: 'flutterteam3-724be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhqOeUCqk0BIm-mEoUcu7KjqCRNN1xDYY',
    appId: '1:48127143523:android:76f044c5c9f167d6761256',
    messagingSenderId: '48127143523',
    projectId: 'flutterteam3-724be',
    storageBucket: 'flutterteam3-724be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUSZfCpdyF7ylPD9HUD0-9fwPIIG8lGTk',
    appId: '1:48127143523:ios:458ef0d4b90f41da761256',
    messagingSenderId: '48127143523',
    projectId: 'flutterteam3-724be',
    storageBucket: 'flutterteam3-724be.firebasestorage.app',
    iosBundleId: 'com.example.flutterteam03',
  );
}
